[tool.poetry]
name = "langchain-template-devops-container-image-code-generator"
version = "1.20240626.1"
description = "Utilizes source code repository files, such as dependency manifests, to generate container image code like Dockerfile and entrypoint shell script using LangChain GenAI. "
authors = ["Sagar Velankar <sagar.velankar@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/langchain-ai/langchain/tree/master/templates/devops-container-image-code-generator"
repository = "https://github.com/langchain-ai/langchain"
documentation = "https://python.langchain.com/v0.2/docs/templates/devops-container-image-code-generator/"

keywords = ["devops", "container-image-code-generator", "devops-platform", "langchain", "genai"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Code Generators",
]

[tool.poetry.dependencies]
python = "^3.9"
langchain-core = ">=0.1.5,<0.3"
langchain-openai = ">=0.0.1"
devops-code-generator = ">=1.0.0,<2.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "langchain_template_devops_container_image_code_generator.chain"
export_attr = "chain"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
